apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: devops
spec:
  limits:
  - default:
       cpu: "500m"
       memory: "512Mi"
    defaultRequest:
      memory: "128Mi"
      cpu: "250m"
    type: Container

