apiVersion: apps/v1
kind: Deployment
metadata:
  name: liv-http
spec:
   replicas: 3
   selector:
     matchLabels:
       app: myapp
   template:
      metadata:
        labels:
           app: myapp
      spec:
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
