apiVersion: v1
kind: Service
metadata:
  name: mypod-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30123
  selector:
    app: mypod
---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
