apiVersion: v1
kind: ResourceQuota
metadata:
  name: devops-rq
  namespace: devops
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
    count/persistentvolumeclaims: "10"
    count/services: "10"
    count/secrets: "5"
    count/configmaps: "10"
    count/replicationcontrollers: "5"
    count/deployments.apps: "10"

