apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
   replicas: 3
   selector:
     matchLabels:
       app: myapp
   template:
      metadata:
        labels:
           app: myapp
      spec:
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "1"
        - name: con2
          image: tomcat:latest
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "1"



