apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-role
  namespace: devops
rules:
  - apiGroups: [ "*" ]
    resources: [ "pods/exec","pods","deployments","configmaps","secrets" ]
    verbs: [ "get", "list","edit","create","update","delete"  ]

##### role binding.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-rb
  namespace: devops
subjects:
- kind: User
  name: aneesh
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops-role
  apiGroup: rbac.authorization.k8s.io

