apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
   replicas: {{ .Values.replica }}
   selector:
     matchLabels:
       {{- include "testapp.labels" . | nindent 8 }}
   template:
      metadata:
        labels:
           {{- include "testapp.labels" . | nindent 12 }}
      spec:
        containers:
        - name: {{ .Values.app.cname }}
          image: {{ .Values.app.image }}
          ports:
          - containerPort: {{ .Values.app.cports.cp }}
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30128
  selector:
    app: myapp
---
