apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
   replicas: 1
   selector:
     matchLabels:
       app: mydb
   template:
      metadata:
        labels:
           app: mydb
      spec:
        containers:
        - name: mydb
          image: mysql:5.7
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
               secretKeyRef:
                  name: mypass
                  key: password
          - name: MYSQL_DATABASE
            value: testdb



---
apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mydb
