---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /data
  volumes:
  - name: myvol
    secret:
      secretName: myfile

