apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-2
spec:
   replicas: 1
   selector:
     matchLabels:
       app: myapp-2
   template:
      metadata:
        labels:
           app: myapp-2
      spec:
        containers:
        - name: con1
          image: wordpress:latest
          ports:
          - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc-2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30129
  selector:
    app: myapp-2
